import 'package:flutter/widgets.dart';
import 'package:lucide_flutter/lucide_flutter.dart';

/// Curated custom-field icon keys shared by picker UI, allowlists, and
/// persisted definition payloads. Keep in sync with backend `IconKeys`.
const customFieldIconKeys = <String>[
  'tag',
  'bookmark',
  'bookmark-check',
  'star',
  'heart',
  'user',
  'users',
  'languages',
  'map-pin',
  'globe',
  'calendar',
  'clock',
  'hash',
  'list',
  'book-open',
  'library',
  'notebook',
  'pen-line',
  'quote',
  'sticky-note',
  'building-2',
  'package',
  'link',
  'award',
  'flag',
  'sparkles',
  'info',
  'coffee',
  'headphones',
  'lightbulb',
  'graduation-cap',
  'trophy',
  'gem',
  'zap',
  'moon',
  'sun',
  'leaf',
  'flame',
  'music',
  'gift',
  'key',
  'lock',
  'eye',
  'bell',
  'home',
  'briefcase',
  'camera',
  'rocket',
  'wine',
  'pizza',
  'palette',
  'compass',
  'wallet',
  'mic',
  'brain',
  'activity',
];

/// Resolves persisted custom-field icon keys through one stable allowlist.
/// Unknown keys deliberately fall back so old data remains renderable.
IconData customFieldIcon(String key) => switch (key) {
  'bookmark' => LucideIcons.bookmark,
  'bookmark-check' => LucideIcons.bookmarkCheck,
  'star' => LucideIcons.star,
  'heart' => LucideIcons.heart,
  'user' => LucideIcons.user,
  'users' => LucideIcons.users,
  'languages' => LucideIcons.languages,
  'map-pin' => LucideIcons.mapPin,
  'globe' => LucideIcons.globe,
  'calendar' => LucideIcons.calendar,
  'clock' => LucideIcons.clock,
  'hash' => LucideIcons.hash,
  'list' => LucideIcons.list,
  'book-open' => LucideIcons.bookOpen,
  'library' => LucideIcons.library,
  'notebook' => LucideIcons.notebook,
  'pen-line' => LucideIcons.penLine,
  'quote' => LucideIcons.quote,
  'sticky-note' => LucideIcons.stickyNote,
  'building-2' => LucideIcons.building2,
  'package' => LucideIcons.package,
  'link' => LucideIcons.link,
  'award' => LucideIcons.award,
  'flag' => LucideIcons.flag,
  'sparkles' => LucideIcons.sparkles,
  'info' => LucideIcons.info,
  'coffee' => LucideIcons.coffee,
  'headphones' => LucideIcons.headphones,
  'lightbulb' => LucideIcons.lightbulb,
  'graduation-cap' => LucideIcons.graduationCap,
  'trophy' => LucideIcons.trophy,
  'gem' => LucideIcons.gem,
  'zap' => LucideIcons.zap,
  'moon' => LucideIcons.moon,
  'sun' => LucideIcons.sun,
  'leaf' => LucideIcons.leaf,
  'flame' => LucideIcons.flame,
  'music' => LucideIcons.music,
  'gift' => LucideIcons.gift,
  'key' => LucideIcons.key,
  'lock' => LucideIcons.lock,
  'eye' => LucideIcons.eye,
  'bell' => LucideIcons.bell,
  'home' => LucideIcons.home,
  'briefcase' => LucideIcons.briefcase,
  'camera' => LucideIcons.camera,
  'rocket' => LucideIcons.rocket,
  'wine' => LucideIcons.wine,
  'pizza' => LucideIcons.pizza,
  'palette' => LucideIcons.palette,
  'compass' => LucideIcons.compass,
  'wallet' => LucideIcons.wallet,
  'mic' => LucideIcons.mic,
  'brain' => LucideIcons.brain,
  'activity' => LucideIcons.activity,
  _ => LucideIcons.tag,
};

/// Whether a datetime custom field should include the clock in display/edit.
/// Empty/unknown modes default to showing time.
bool customFieldShowsTime(String textMode) => textMode != 'date';
